apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bootstrap
  namespace: argocd-system
spec:
  description: Bootstrap project for app-of-apps and projects ArgoCD applications.
  sourceRepos:
    - https://github.com/LiferayCloud/lcp-examples.git
  destinations:
    - name: in-cluster
      namespace: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: ApplicationSet
    - group: argoproj.io
      kind: AppProject
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
