projects:
  - name: bootstrap
    description: Bootstrap project for app-of-apps and projects ArgoCD applications.
    namespace: argocd-system
    sourceRepos:
      - "https://github.com/LiferayCloud/lcp-examples.git"
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
    namespaceResourceWhitelist:
      - group: "argoproj.io"
        kind: Application
      - group: "argoproj.io"
        kind: ApplicationSet
      - group: "argoproj.io"
        kind: AppProject
      - group: ""
        kind: Service
      - group: "apps"
        kind: Deployment
    destinations:
      - name: in-cluster
        namespace: argocd-system
      - name: in-cluster
        namespace: lcp-system

applications:
  - name: lcp
    namespace: argocd-system
    project: bootstrap
    source:
      repoURL: https://github.com/LiferayCloud/lcp-examples.git
      targetRevision: master
      path: ./helm-charts/lcp
      helm:
        releaseName: lcp
        valueFiles:
          - values.yaml
    destination:
      name: in-cluster
      namespace: lcp-system
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: false
        selfHeal: true
